### ISSUE TITLE
As a user, I want to be able to view my game history and track my progress.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/client#44]
### Acceptance Criteria:
- [x] Users can view their game history, including single-player and multiplayer games.
- [x] Users can view their score and progress in each game.
- [x] Users can filter their game history by different criteria such as date, game type, etc.

### Development Tasks:
- [x] sopra-fs23-group-26/client#45
- [x] sopra-fs23-group-26/client#46
- [x] sopra-fs23-group-26/server#104
