### ISSUE TITLE
As a logged-in user, I could gain some credits when winning and see rankings between my friends.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/client#47]
### Acceptance Criteria:
- [x] A user can view his or her accumulated game credits and ranking when logging in.
- [x] When a user reaches certain rankings, he or she will be eligible to receive certain gifts as a reward.

### Development Tasks:
- [x] sopra-fs23-group-26/client#48
- [x] sopra-fs23-group-26/client#49
- [x] sopra-fs23-group-26/server#107

**Comment by Jess688688** [comment]
bca3025c0ee57b5974d8289766c615993cd24d4e
